(ns hive-mcp.tools.consolidated.session-config
  "Typed config for the consolidated `session` MCP tool via hive-di defconfig.

   Replaces three raw `(System/getenv \"CLAUDE_SWARM_SLAVE_ID\")` reads in
   `hive-mcp.tools.consolidated.session` (handle-whoami, wrap-async!,
   handle-complete) with a single declarative config surface.

   Env vars:
     CLAUDE_SWARM_SLAVE_ID — slave-id of the calling ling, used as a
                             fallback agent identity when callers don't
                             pass `agent_id` and the dynamic context
                             store has no current-agent-id.

   Generated by defconfig:
     SessionToolConfig          — ADT
     SessionToolConfig-fields   — field registry
     SessionToolConfig-schema   — Malli schema
     resolve-SessionToolConfig  — resolver fn (0/1/2 arity, returns Result)

   Field is declared `:required false` because the env var is genuinely
   optional — coordinator processes resolve to nil here and the call sites
   then fall back to literal \"unknown\" / \"coordinator\" sentinels."
  (:require [hive-di.core :refer [defconfig env]]
            [hive-dsl.result :as r]))

(defconfig SessionToolConfig
  :swarm-slave-id (env "CLAUDE_SWARM_SLAVE_ID"
                       :type :string
                       :required false
                       :doc "Ling's slave-id from CLAUDE_SWARM_SLAVE_ID env. Optional; nil for coordinator processes."))

(defn resolve!
  "Resolve SessionToolConfig with optional overrides.
   Returns the resolved map directly. Throws if resolution fails
   (only possible when an override is type-invalid; defaults guarantee
   resolution otherwise)."
  ([] (resolve! {}))
  ([overrides]
   (let [result (resolve-SessionToolConfig overrides)]
     (if (r/ok? result)
       (:ok result)
       (throw (ex-info "SessionToolConfig resolution failed"
                       {:result result :overrides overrides}))))))

(defn swarm-slave-id
  "Return CLAUDE_SWARM_SLAVE_ID resolved via defconfig.
   Returns nil when unset (coordinator / non-swarm processes)."
  []
  (:swarm-slave-id (resolve!)))
