(ns hive-mcp.hivemind.conversation
  "Inter-Ling Conversation Protocol — pure protocol layer (Calculations).

   Implements the three primitives from decision 20260401222011-493b1a6e:
     - tell    : fire-and-forget DM         (no correlation, no blocking)
     - ask     : DM that blocks the sender  (correlated via :ask-id → promise-chan)
     - respond : answer to a prior ask      (delivers a value to the ask's promise-chan)

   Stratification (decision 20260415135102-1d300fdc):
     - This namespace is Calculations + a tiny Data layer (the pending-asks
       atom). It does NOT call NATS, the bounded-atom registry, the
       event-bus, or any IO boundary. Effect handlers are responsible for
       transport and persistence.
     - The public functions return *event maps* (envelopes), the caller
       (interceptors / event handlers) are responsible for dispatching
       them onto the bus.
     - `register-ask!` / `deliver-response!` / `cancel-ask!` operate on a
       defonce'd atom. This is the only mutable state in the protocol layer
       and is bounded by sweep + per-call dissoc.

   ask-id correlation:
     A `random-uuid` string is generated by the sender. The ask map is parked
     under `pending-asks` with a one-shot core.async promise-chan. The receiver
     calls `deliver-response!` with the same ask-id — the value lands on the
     promise-chan and the sender's parked `alt!!` returns. On timeout the
     entry is dissoc'd and the response (if it ever arrives) is dropped.

   Why promise-chan (not NATS req-reply)?
     - Local-first: works without a backbone. NATS bridge merely re-injects
       respond messages into deliver-response! so the same correlation table
       handles both transports.
     - Cancellable + timeout-safe via core.async/alt!!.
     - Mirrors existing hivemind.messaging/ask! shape for the human-loop case.
     - One mechanism, two transports — matches Stratification."

  (:require [clojure.core.async :as async :refer [alt!! timeout]]
            [taoensso.timbre :as log]))
;; Copyright (C) 2026 Pedro Gomes Branquinho (BuddhiLW) <pedrogbranquinho@gmail.com>
;;
;; SPDX-License-Identifier: AGPL-3.0-or-later

;; =============================================================================
;; State (Data layer — single atom, bounded by per-ask dissoc)
;; =============================================================================

(defonce ^{:doc "Map of ask-id (string) -> {:from agent-id
                                              :to   agent-id
                                              :question string
                                              :timestamp long
                                              :response-chan core.async/promise-chan}.
   Cleared on respond / timeout / cancel."}
  pending-asks
  (atom {}))

(def ^:const default-ask-timeout-ms
  "Default block-on-ask timeout (5 minutes)."
  300000)

;; =============================================================================
;; Helpers (pure)
;; =============================================================================

(defn- now-ms [] (System/currentTimeMillis))

(defn- new-ask-id []
  (str (random-uuid)))

;; =============================================================================
;; Envelope constructors (pure)
;; =============================================================================

(defn tell-envelope
  "Pure constructor for a :conversation/tell event envelope.

   Required: :from, :to, :message
   Optional: :project-id, :data (extra payload), :timestamp (defaults to now)"
  [{:keys [from to message project-id data timestamp]
    :or   {timestamp (now-ms)}}]
  {:pre [(string? from) (string? to) (some? message)]}
  (cond-> {:event-type :conversation/tell
           :from       from
           :to         to
           :message    message
           :timestamp  timestamp}
    project-id (assoc :project-id project-id)
    data       (assoc :data data)))

(defn ask-envelope
  "Pure constructor for a :conversation/ask event envelope. Generates ask-id
   if not supplied. Does NOT register the ask (caller decides — keeps this
   pure)."
  [{:keys [from to question ask-id project-id data timestamp]
    :or   {timestamp (now-ms)}}]
  {:pre [(string? from) (string? to) (some? question)]}
  (cond-> {:event-type :conversation/ask
           :from       from
           :to         to
           :ask-id     (or ask-id (new-ask-id))
           :question   question
           :timestamp  timestamp}
    project-id (assoc :project-id project-id)
    data       (assoc :data data)))

(defn respond-envelope
  "Pure constructor for a :conversation/respond event envelope.
   Carries the original ask-id for correlation."
  [{:keys [from to ask-id answer project-id data timestamp]
    :or   {timestamp (now-ms)}}]
  {:pre [(string? from) (string? to) (string? ask-id) (some? answer)]}
  (cond-> {:event-type :conversation/respond
           :from       from
           :to         to
           :ask-id     ask-id
           :answer     answer
           :timestamp  timestamp}
    project-id (assoc :project-id project-id)
    data       (assoc :data data)))

;; =============================================================================
;; Promise registry (mutates pending-asks atom — boundary on this ns)
;; =============================================================================

(defn register-ask!
  "Register a pending ask. Returns the response-chan (1-buffer promise-style chan).

   Side effect: assoc into pending-asks. Pair with `await-response!` to park,
   or with `deliver-response!` from the receiver side. `cancel-ask!` cleans up."
  [{:keys [ask-id from to question]}]
  {:pre [(string? ask-id) (string? from) (string? to)]}
  (let [response-chan (async/promise-chan)]
    (swap! pending-asks assoc ask-id
           {:ask-id        ask-id
            :from          from
            :to            to
            :question      question
            :timestamp     (now-ms)
            :response-chan response-chan})
    response-chan))

(defn deliver-response!
  "Deliver a response value to the promise-chan registered under ask-id.
   No-op (returns false, logs) if the ask is unknown or already resolved.

   Receivers (event handlers, NATS subscribers) call this with the parsed
   answer payload."
  [ask-id answer]
  (if-let [{:keys [response-chan]} (get @pending-asks ask-id)]
    (do
      (async/put! response-chan answer)
      (swap! pending-asks dissoc ask-id)
      (log/debug "[conversation] response delivered for ask-id" ask-id)
      true)
    (do
      (log/warn "[conversation] no pending ask for id" ask-id)
      false)))

(defn cancel-ask!
  "Drop a pending ask without delivering. Used on timeout / sender abort.
   Returns true if an entry was removed."
  [ask-id]
  (let [removed? (boolean (get @pending-asks ask-id))]
    (swap! pending-asks dissoc ask-id)
    removed?))

(defn pending-ask
  "Inspect a pending ask by id (read-only). Returns nil if absent."
  [ask-id]
  (get @pending-asks ask-id))

(defn pending-count
  "Number of pending asks. For tests / status."
  []
  (count @pending-asks))

(defn clear-pending!
  "Drop every pending ask. For tests only."
  []
  (reset! pending-asks {}))

;; =============================================================================
;; Sender-side blocking helper (parks until response or timeout)
;; =============================================================================

(defn await-response!
  "Park on the response-chan for an already-registered ask. Returns the
   delivered answer, or {:timeout true :ask-id <id>} on timeout. Cleans the
   pending entry on either path.

   NB: blocks the calling thread (alt!!). Designed for tool-call boundaries
   where the agentic loop is parked on a single thread."
  [ask-id & {:keys [timeout-ms] :or {timeout-ms default-ask-timeout-ms}}]
  (if-let [{:keys [response-chan]} (get @pending-asks ask-id)]
    (let [result (alt!!
                   response-chan ([v] v)
                   (timeout timeout-ms) {:timeout true :ask-id ask-id})]
      (swap! pending-asks dissoc ask-id)
      result)
    {:no-such-ask true :ask-id ask-id}))

;; =============================================================================
;; Convenience: full ask round-trip envelope (still pure — no transport)
;; =============================================================================

(defn build-ask!
  "Construct an ask envelope AND register the promise-chan in one go.
   Returns {:envelope ... :ask-id ... :response-chan ...}.

   Caller is responsible for dispatching the envelope onto the bus
   (an event handler / interceptor will route it to NATS or piggyback)."
  [{:keys [from to question project-id data timeout-ms] :as opts}]
  (let [env (ask-envelope (dissoc opts :timeout-ms))
        ch  (register-ask! env)]
    {:envelope      env
     :ask-id        (:ask-id env)
     :response-chan ch}))
